apiVersion: v1
kind: Deployment
metadata:
  name: iibmq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: iibmq
        tier: one
    spec:
      containers:
      - name: iib-mq-pj-1
        image: registry.ng.bluemix.net/pj_docker_images/iib-mq-pj-1:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          # value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
           value: env
        ports:
- containerPort: 4414